#!/usr/bin/env node

// Emits dist/THIRD-PARTY-NOTICES.txt.
//
// The input is runtime-npm-modules.txt -- the set of npm packages esbuild
// actually pulled into the bundle, written by build.js from the metafile --
// so the notice can never list a module the bundle does not contain, nor miss
// one it does. Packages that ship no license text of their own, and the binary
// assets that are not npm packages at all (webfonts, background SVGs), come
// from notices/overrides.json. A bundled package with neither is a hard error:
// silence is how the notices went missing in the first place.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const LICENSE_FILE = /^(licen[cs]e|copying|notice)(\.|$)/i;
const RULE = "=".repeat(78);

const readModules = file =>
    fs.readFileSync(file, "utf8")
            .split("\n")
            .filter(line => line.trim() !== "")
            .map(line => {
                const at = line.lastIndexOf(" ");
                return { name: line.slice(0, at), version: line.slice(at + 1) };
            });

const findLicenseText = dir => {
    const hit = fs.readdirSync(dir).find(entry => LICENSE_FILE.test(entry));
    return hit ? fs.readFileSync(path.join(dir, hit), "utf8").trimEnd() : null;
};

const section = (title, body) => `${RULE}\n${title}\n${RULE}\n\n${body}\n\n`;

// Notes are prose in a JSON file, so they arrive as one long line.
const wrap = (text, width = RULE.length) => text
        .split(/\s+/)
        .reduce((lines, word) => {
            const last = lines[lines.length - 1];
            if (last === "" || `${last} ${word}`.length <= width)
                lines[lines.length - 1] = last === "" ? word : `${last} ${word}`;
            else
                lines.push(word);
            return lines;
        }, [""])
        .join("\n");

export const buildNotices = (outdir, {
    modulesFile = "runtime-npm-modules.txt",
    noticesDir = "notices",
    modulesRoot = "node_modules",
} = {}) => {
    const overrides = JSON.parse(fs.readFileSync(path.join(noticesDir, "overrides.json"), "utf8"));
    const modules = readModules(modulesFile);

    let out = `Third-party notices for the SHR-RS Cockpit plugin
${RULE}

The plugin itself is LGPL-2.1-or-later; see LICENSE. Everything below is
third-party code and data compiled into dist/index.js, dist/index.css or
dist/assets/ and redistributed with it, listed with the terms it is
redistributed under.

Generated by build-notices.js from the modules esbuild resolved into the
bundle. dist/index.js.LEGAL.txt holds the same packages' inline banner
comments as esbuild extracted them; this file is the complete list.

`;

    for (const { name, version } of modules) {
        const dir = path.join(modulesRoot, ...name.split("/"));
        const meta = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
        const override = overrides.packages?.[name];
        const text = findLicenseText(dir) ?? (override
            ? fs.readFileSync(path.join(noticesDir, override.file), "utf8").trimEnd()
            : null);
        if (text === null)
            throw new Error(`bundled module ${name} ships no license file and has no notices/overrides.json entry`);

        const head = [`${name} ${version}`, `License: ${meta.license ?? "see text below"}`];
        if (meta.homepage)
            head.push(`Homepage: ${meta.homepage}`);
        if (override?.note)
            head.push("", wrap(override.note));
        out += section(head.join("\n"), text);
    }

    for (const asset of overrides.assets ?? []) {
        const head = [asset.name, `License: ${asset.license}`, wrap(asset.origin)];
        if (asset.note)
            head.push("", wrap(asset.note));
        out += section(head.join("\n"), fs.readFileSync(path.join(noticesDir, asset.file), "utf8").trimEnd());
    }

    const target = path.join(outdir, "THIRD-PARTY-NOTICES.txt");
    fs.writeFileSync(target, out.trimEnd() + "\n");
    return { target, packages: modules.length, assets: (overrides.assets ?? []).length };
};

if (process.argv[1] && import.meta.filename === path.resolve(process.argv[1])) {
    const { target, packages, assets } = buildNotices(path.resolve("dist"));
    console.log(`Wrote ${path.relative(process.cwd(), target)} (${packages} packages, ${assets} bundled assets)`);
}
